import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newDb} from 'pg-mem';
process.env.FRONTEND_URL='http://localhost:3000';process.env.ADMIN_EMAILS='owner@example.com';process.env.NODE_ENV='test';
const {useDatabase,migrate,pool:unused}=await import('../src/lib/database');
const memory=newDb();const Pg=memory.adapters.createPg();const pool=new Pg.Pool();useDatabase(pool);await migrate();
const {createAccount,hashPassword,verifyPassword}=await import('../src/auth');
const {createApp}=await import('../src/app');
await createAccount('owner@example.com','Owner','owner-secure-password-123','admin','UBL Demo');await createAccount('reviewer@example.com','Reviewer','reviewer-password-456','learner','UBL Demo');await createAccount('manager@example.com','Manager','manager-password-789','manager','HR');
const server=createApp().listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const address=server.address() as any;const base=`http://127.0.0.1:${address.port}`;
async function api(path:string,cookie='',body?:any,origin='http://localhost:3000'){const response=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{}),Origin:origin},body:body?JSON.stringify(body):undefined});return {status:response.status,data:await response.json() as any,cookie:response.headers.get('set-cookie')?.split(';')[0]||''};}
await test('portable runtime integration with PostgreSQL-compatible SQL',async()=>{try{
 assert.equal((await api('/health')).status,200);assert.equal((await api('/api/admin')).status,401);
 const forged=await fetch(base+'/api/admin',{headers:{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.com'}});assert.equal(forged.status,401);
 const bad=await api('/api/auth/login','',{email:'reviewer@example.com',password:'wrong'});assert.equal(bad.status,401);
 const login=await api('/api/auth/login','',{email:'reviewer@example.com',password:'reviewer-password-456'});assert.equal(login.status,200);assert.ok(login.cookie.startsWith('learn_session='));const learner=login.cookie;
 assert.equal((await api('/api/auth/me',learner)).data.role,'learner');assert.equal((await api('/api/admin',learner)).status,403);assert.equal((await api('/api/auth/accounts',learner,{email:'fake@example.com',password:'long-enough-password',role:'admin',department:'HR'})).status,403);
 assert.equal((await api('/api/learning',learner)).data.state.sessions,0);const generated=await api('/api/learning',learner,{action:'generate',source:'topic',topic:'phishing',config:{language:'English',level:'Beginner',duration:5,voice:true,gamification:true,reviewDays:1}});assert.equal(generated.status,200);assert.equal(generated.data.state.activeId,'p1');assert.equal('correctId' in generated.data.state.course.activities[0],false);
 const answer={action:'answer',activityId:'p1',optionId:'1',confidence:80,seconds:30};assert.equal((await api('/api/learning',learner,answer)).status,200);const resumed=await api('/api/learning',learner);assert.equal(resumed.data.state.history.length,1);assert.equal(resumed.data.state.xp,25);assert.equal((await api('/api/learning',learner,answer)).status,400);
 assert.equal((await api('/api/learning',learner,{action:'generate',source:'topic',topic:'employee wellbeing policy'})).status,503);
 assert.equal((await api('/api/learning',learner,{action:'hint'},'http://attacker.example')).status,403);
 const manager=(await api('/api/auth/login','',{email:'manager@example.com',password:'manager-password-789'})).cookie;assert.equal((await api('/api/admin',manager)).status,200);assert.equal((await api('/api/admin',manager,{action:'member',member:{email:'new@example.com',department:'HR',role:'admin'}})).status,403);
 const owner=(await api('/api/auth/login','',{email:'owner@example.com',password:'owner-secure-password-123'})).cookie;assert.equal((await api('/api/learning',owner,{action:'generate',source:'topic',topic:'negotiation'})).status,200);const report=await api('/api/admin',owner);assert.equal(report.status,200);assert.ok(report.data.learners.some((r:any)=>r.responses===1));assert.equal('payload' in report.data.learners[0],false);
 assert.equal((await api('/api/admin',owner,{action:'publish',department:'HR'})).status,200);const published=(await api('/api/admin',owner)).data.library[0];assert.equal((await api('/api/learning',learner)).data.library.length,0);assert.equal((await api('/api/learning',learner,{action:'library',id:published.id})).status,400);assert.equal((await api('/api/learning',manager,{action:'library',id:published.id})).status,200);
 assert.equal((await api('/api/admin',owner,{action:'publish',department:'All'})).status,200);assert.equal((await api('/api/learning',learner)).data.library.length,1);
 assert.equal((await api('/api/auth/accounts',owner,{email:'panel@example.com',password:'panel-password-123',role:'learner',department:'UBL Demo'})).status,200);assert.equal((await api('/api/auth/login','',{email:'panel@example.com',password:'panel-password-123'})).status,200);
 const document={filename:'wellbeing.docx',referenceKind:'section',pages:[{page:1,text:'Employee wellbeing policy. Managers review workload regularly. Employees can request confidential support and agree on priorities. Never demand personal medical information during a public team discussion. Follow up within seven days.'}]};
 assert.equal((await api('/api/advanced','')).status,401);
 assert.equal((await api('/api/advanced',learner,{action:'index',document})).status,200);
 assert.equal((await api('/api/advanced',learner,{action:'search',query:'workload'})).data.matches.length,1);
 assert.equal((await api('/api/advanced',manager,{action:'search',query:'workload'})).data.matches.length,0);
 assert.equal((await api('/api/advanced',learner,{action:'preferences',enabled:true,cadenceDays:2})).status,200);
 assert.equal((await api('/api/advanced',learner)).data.preference.enabled,1);
 assert.equal((await api('/api/advanced',learner,{action:'chat',text:'Explain'})).status,503);
 assert.equal((await api('/api/reminders/run',learner,{})).status,403);
 assert.equal((await api('/api/reminders/run',owner,{})).status,503);
 const assetId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';const account=(await api('/api/auth/me',learner)).data.email;const row=await pool.query('SELECT id FROM app_users WHERE email=$1',[account]);const bytes=Buffer.from([137,80,78,71,0,255]);await pool.query('INSERT INTO generated_assets (id,owner_id,object_key,activity_id,created_at,image_data) VALUES ($1,$2,$3,$4,$5,$6)',[assetId,row.rows[0].id,'test','test',new Date().toISOString(),bytes.toString('base64')]);
 const image=await fetch(base+'/api/assets/'+assetId,{headers:{cookie:learner}});assert.equal(image.status,200);assert.deepEqual(Buffer.from(await image.arrayBuffer()),bytes);assert.equal((await fetch(base+'/api/assets/'+assetId,{headers:{cookie:manager}})).status,404);
 assert.equal((await api('/api/auth/logout',learner,{})).status,200);assert.equal((await api('/api/auth/me',learner)).status,401);
 const hash=await hashPassword('sample-password');assert.ok(!hash.includes('sample-password'));assert.equal(await verifyPassword('sample-password',hash),true);assert.equal(await verifyPassword('wrong',hash),false);
 }finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await pool.end();await unused.end();}});
