import { Activity, Course } from './learning';
const make=(id:string,concept:string,difficulty:number,title:string,scenario:string,kind:'email'|'conversation'|'brief',from:string,subject:string,body:string,options:string[],correct:number,explanation:string,hint:string):Activity=>({id,concept,difficulty,title,scenario,visual:{kind,from,subject,body},options:options.map((label,i)=>({id:String(i),label})),correctId:String(correct),explanation,hint,evidence:explanation,sourceRef:'Prepared instructional scenario · not an external source citation'});
const phishing:Activity[]=[
make('p1','Sender verification',1,'Spot the phish','A message appears in your work inbox. What is the safest first action?','email','IT Support <support@ubl-security-check.example>','Action needed: your password expires today','Your account will be closed in 30 minutes. Confirm your password at https://ubl-login-check.example/verify. Do not contact the help desk, as they are overloaded.', ['Enter your password before the deadline','Verify the request through your known IT channel','Forward it to colleagues so they can act'],1,'A display name and a familiar-looking domain do not prove identity. Contact IT using a channel you already trust. Urgency and discouraging verification are warning signs.','Look at the sender domain and the instruction not to contact IT.'),
make('p2','Link safety',1,'Where does this link go?','The label looks reassuring. Inspect the destination before deciding.','email','Benefits Team <benefits@company.example>','Review your benefits','Displayed link: Employee benefits portal\nActual destination: https://company-benefits-verify.example/login\nPlease sign in using your company password.', ['Use the link because the label says portal','Open the benefits portal from a saved bookmark','Send your password by reply instead'],1,'Link labels can hide a different destination. Use a known bookmark or type the official address rather than trusting the link.','Compare what the link says with where it actually goes.'),
make('p3','Safe response',1,'You already clicked','You opened a suspicious page and entered your password. What comes next?','brief','Incident scenario','Act promptly','The page asked for your company credentials. You submitted them before noticing the unusual address.', ['Wait and see whether anything happens','Delete the message and keep it private','Report immediately and follow IT guidance to secure the account'],2,'Prompt reporting allows your security team to contain the incident. Follow their instructions for password changes and account protection. Deleting the email alone cannot undo exposure.','Your next action should help the security team respond.'),
make('p4','Sender verification',2,'A familiar name, a new request','A message claims to be from your manager. The request is unusual.','conversation','Manager on a new number','A quick favour','I am in a confidential meeting. Buy gift cards now and send the codes here. I will reimburse you. Please do not call.', ['Verify with your manager on their known number','Buy one card as a low-risk trial','Ask the new number for the manager’s full name'],0,'Knowing a name is not proof of identity. Verify an unusual financial request using a contact channel you already know, especially if the sender discourages a call.','Verification must happen outside this new conversation.'),
make('p5','Link safety',2,'The QR code shortcut','A poster offers a shortcut to an employee benefit. What should you do?','brief','Office noticeboard','Scan to claim your reward','A newly attached QR sticker points to a page asking for your work credentials. It promises a reward that expires today.', ['Scan and sign in quickly','Find the benefit through the official employee portal','Share the QR code with your team'],1,'QR codes hide destinations until scanned. Confirm the offer through an official channel and use the known portal instead of an unverified login page.','A QR code deserves the same checks as an emailed link.'),
make('p6','Safe response',2,'A supplier changes bank details','A supplier email asks for payment to a new account. The thread looks familiar.','email','Known supplier','Updated payment instructions','We have changed our bank account. Please use the attached details for today’s payment. Our finance contact is away, so please confirm only by email.', ['Pay because it is part of an existing thread','Verify independently using the supplier contact on record','Reply to the message asking if it is genuine'],1,'A compromised mailbox can send messages in a real thread. Validate bank-detail changes through an independent, previously known contact and your payment-control process.','A real email thread can still contain a fraudulent request.'),
make('p7','Sender verification',3,'An internal account is compromised','The address is genuinely internal, but the request breaks normal practice.','email','colleague@company.example','Please share customer records','Upload the customer export to this external folder today. Approval is already handled. Skip the normal ticket.', ['Trust it because the domain is internal','Verify the purpose and approval through established channels','Upload only half the file'],1,'A valid sender address is one signal, not a guarantee. Compromised accounts can send harmful requests. Verify unusual data transfers and follow the normal approval process.','Consider the request itself, even when the sender address is valid.'),
make('p8','Link safety',3,'A secure padlock, an unsafe site','The browser displays HTTPS. Is that enough to trust a login page?','brief','Browser inspection','https://secure-company-help.example','The page has a padlock and a copied company logo. It asks you to approve an unexpected login.', ['HTTPS means it belongs to your employer','The logo proves ownership','Check the exact official domain and verify the login request'],2,'HTTPS protects the connection to that site. It does not prove the site belongs to your employer or that the request is legitimate.','Encryption and identity are different questions.'),
make('p9','Safe response',3,'Pressure from a senior leader','Someone claims to be a senior leader and demands a confidential transfer.','conversation','Executive request','Do this outside the usual process','The caller knows your role and projects. They insist on bypassing approval because the transfer is urgent.', ['Proceed because the caller knows internal details','Follow payment controls and independently verify the request','Transfer a smaller amount without approval'],1,'Public or stolen information can make a caller sound convincing. Independent verification and required approvals still apply to urgent senior requests.','Authority and urgency do not replace approval controls.'),
make('p10','Sender verification',1,'A second look at identity','A message claims to be from payroll. How can you verify it independently?','email','Payroll <payroll@employee-check.example>','Confirm your salary account','Reply with your account details today. Do not use the usual payroll portal.', ['Reply asking the sender to confirm their job title','Contact payroll using the directory you already use','Send a screenshot of your bank account'],1,'Use a known channel such as your internal directory. A claim in the suspicious message cannot independently verify the sender.','Use contact details that did not come from this message.'),
make('p11','Link safety',1,'Take the known route','An email says you have a document to review. Choose a safe way to find it.','brief','Shared document notice','A file is waiting','The message provides an unfamiliar sign-in link, but your organization has a known document portal.', ['Go directly to the known portal and look for the document','Use the unfamiliar link because it saves time','Ask someone else to enter their password first'],0,'A known portal avoids relying on an unverified login link. If the document is not there, verify the request with the sender through a known channel.','You already have a trusted route to the service.'),
make('p12','Safe response',1,'Report without spreading it','You suspect a work email is phishing. What should you do?','email','Unknown sender','Unexpected attachment','The message asks you to open an attachment to receive a reward. You did not request it.', ['Forward the attachment to every colleague','Open it to collect evidence','Use the organization’s reporting process without opening the attachment'],2,'Report through your approved process and avoid opening or spreading the attachment. Your security team can investigate safely.','Reporting does not require you to open the suspicious attachment.')];
const negotiation:Activity[]=[
make('n1','Interests',1,'What is behind the request?','A team member wants a deadline extension. Start the discussion.','conversation','Team member','The deadline','I need another week. This deadline is impossible.', ['Reject it immediately','Ask what is preventing completion and what support would help','Offer two weeks without asking why'],1,'Ask about the underlying constraint before trading deadlines. Understanding the interest helps you find options beyond accepting or refusing the first demand.','Find the problem behind the stated position.'),
make('n2','Alternatives',1,'Prepare before agreeing','A vendor offers a higher price. What should you clarify first?','brief','Vendor discussion','Before the meeting','The proposed renewal is above budget. You have time to compare alternatives.', ['Identify realistic alternatives and your limits','Threaten to leave without checking options','Reveal the maximum budget immediately'],0,'Knowing your alternatives and limits helps you assess an offer calmly. An unverified threat can damage trust and your negotiating position.','Know what you will do if no agreement is reached.'),
make('n3','Trade-offs',1,'Make a useful exchange','A vendor cannot lower the price. You can adjust scope and timing.','conversation','Vendor','The offer','The unit price is fixed, but delivery timing and support are flexible.', ['Repeat the same price demand','Accept without discussion','Explore timing, scope and support as a package'],2,'A package can create value across several terms. Explore what each side values rather than treating price as the only possible variable.','Look for terms that matter differently to each side.'),
make('n4','Interests',2,'Two departments, one resource','Both departments need the same analyst this week.','conversation','Operations and Finance','A scheduling conflict','Operations needs a daily report. Finance needs a one-off analysis by Thursday.', ['Allocate identical time without discussing needs','Clarify deadlines and minimum deliverables for each team','Give everything to the louder manager'],1,'Different deliverables and deadlines can allow a schedule that meets both interests. Equal time is not always the most useful solution.','Explore timing and deliverables before dividing the resource.'),
make('n5','Alternatives',2,'A deadline in the negotiation','A supplier says the offer expires today.','brief','Supplier','An expiring offer','The supplier pressures you to accept. A credible alternative would take another week to assess.', ['Assess the cost of waiting against your alternative','Accept immediately to avoid losing the offer','Invent a competing offer'],0,'Compare the cost of delay and the value of alternatives. Pressure does not remove the need for a reasoned decision.','What is the actual cost of waiting?'),
make('n6','Trade-offs',2,'Conditional concessions','A customer asks for a discount and faster delivery.','conversation','Customer','Can you do both?','Your team has limited capacity. A longer commitment could justify a lower price.', ['Give both concessions immediately','Offer a discount conditional on a longer commitment','Refuse to discuss any options'],1,'Make concessions conditional and clear. Exchanging terms can preserve value while addressing the customer’s needs.','Connect what you give to something the other side can offer.'),
make('n7','Interests',3,'Resolve hidden concerns','A partner rejects your proposed timeline repeatedly.','conversation','Partner','Another delay','The partner agrees the timeline is feasible but hesitates to commit publicly.', ['Apply more pressure','Explore the risk or accountability concern behind the hesitation','Treat silence as acceptance'],1,'Feasibility and willingness are different. Ask about the concern and address it without assuming the partner is simply being difficult.','Explore what makes committing difficult.'),
make('n8','Alternatives',3,'Walk-away discipline','The latest offer is below your agreed minimum value.','brief','Negotiation team','The final offer','Your team has a credible alternative but has spent weeks in this discussion.', ['Accept because of time already spent','Evaluate future value against your alternative and limits','Lower your limit without consulting the team'],1,'Time already spent is a sunk cost. Compare future outcomes with your alternatives and agreed limits.','Past effort does not change the future value of an offer.'),
make('n9','Trade-offs',3,'Close the agreement clearly','Both sides verbally agree to a complex package.','brief','Agreement','The closing step','Price, delivery milestones and support were discussed, with different assumptions about acceptance.', ['Start work without written terms','Confirm obligations, milestones and acceptance in writing','Only write down the price'],1,'Confirm the full agreement to reduce conflicting assumptions. Include who does what, when and how completion is accepted.','The agreement needs to capture more than price.')];
const service:Activity[]=negotiation.map((a,i)=>({...a,id:'s'+i,concept:['Listening','Resolution','Follow-through'][i%3],title:['Listen before solving','Choose a fair resolution','Close the loop'][i%3],scenario:'A customer has been charged twice and is frustrated. What is your best next step?',visual:{kind:'conversation',from:'Customer',subject:'Duplicate charge',body:'I have contacted you twice. I need this sorted, and I do not want to explain everything again.'},options:[{id:'0',label:'Acknowledge the issue, check the record and explain the next step'},{id:'1',label:'Ask them to start a new request without checking history'},{id:'2',label:'Promise an immediate refund before verifying the charge'}],correctId:'0',explanation:'Acknowledge the frustration, use the existing history and explain what you can do next. Avoid making promises before checking the facts. Give a clear owner and update time.',hint:'Make it easier for the customer without promising an unverified outcome.'}));
export function prepared(topic:string,level:string,language:string,duration:number):Course|null{
 if(language!=='English')return null;
 const key=topic.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
 const kind=['phishing','phishing social engineering','cybersecurity awareness phishing social engineering'].includes(key)?'phishing':['negotiation','negotiation skills for managers'].includes(key)?'negotiation':key==='customer service essentials'?'service':null;
 if(!kind)return null;
 const activities=kind==='phishing'?phishing:kind==='negotiation'?negotiation:service;
 const concepts=Array.from(new Set(activities.map(a=>a.concept)));
 return {title:kind==='phishing'?'Phishing & social engineering':kind==='negotiation'?'Negotiation skills for managers':'Customer service essentials',objectives:concepts.map(c=>'Apply '+c.toLowerCase()+' in a practical situation'),concepts,activities,mode:'Prepared demo',source:'Prepared instructional scenarios',level,language,duration};
}
