import express from 'express';
import {z} from 'zod';
import {pool} from './lib/database';
import {authenticate,currentUser,createAccount,readToken,sessionCookie,startSession,tokenHash,verifyPassword} from './auth';
import {identity} from './lib/admin';
import * as learning from './routes/learning';
import * as admin from './routes/admin';
import * as advanced from './routes/advanced';
import * as assets from './routes/assets';
import * as reminders from './routes/reminders';
export function createApp(){const app=express();app.disable('x-powered-by');app.set('trust proxy',1);app.use(express.text({type:'application/json',limit:'7mb'}));
 const frontendOrigin=new URL(process.env.FRONTEND_URL||'http://localhost:3000').origin;
 app.use((req,res,next)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');if(req.headers.origin&&req.headers.origin!==frontendOrigin)return res.status(403).json({error:'Invalid request origin'});if(!['GET','HEAD','OPTIONS'].includes(req.method)&&!req.is('application/json'))return res.status(415).json({error:'Use an application/json request.'});next();});
 app.get('/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({status:'ok'});}catch{res.status(503).json({status:'database_unavailable'});}});
 const attempts=new Map<string,{count:number;until:number}>();
 app.post('/api/auth/login',async(req,res)=>{try{const body=z.object({email:z.string().email().max(254),password:z.string().min(1).max(200)}).parse(JSON.parse(req.body));const email=body.email.trim().toLowerCase();const key=(req.ip||'')+'|'+email;const now=Date.now();for(const [k,v]of attempts)if(v.until<now)attempts.delete(k);const bucket=attempts.get(key)||{count:0,until:now+15*60000};if(bucket.count>=8)return res.status(429).json({error:'Too many login attempts. Try again in 15 minutes.'});bucket.count++;attempts.set(key,bucket);const {rows}=await pool.query('SELECT id,password_hash FROM app_users WHERE email=$1',[email]);if(!rows[0]||!await verifyPassword(body.password,rows[0].password_hash))return res.status(401).json({error:'Email or password is incorrect.'});attempts.delete(key);const token=await startSession(rows[0].id);res.setHeader('Set-Cookie',sessionCookie(token));return res.json({ok:true});}catch(e){return res.status(e instanceof z.ZodError?400:500).json({error:e instanceof z.ZodError?'Enter a valid email and password.':'Login is temporarily unavailable.'});}});
 app.post('/api/auth/logout',async(req,res)=>{try{const token=readToken(req.headers.cookie);if(token)await pool.query('DELETE FROM app_sessions WHERE token_hash=$1',[tokenHash(token)]);res.setHeader('Set-Cookie',sessionCookie('',true));res.json({ok:true});}catch{res.status(503).json({error:'Sign out failed. Try again.'});}});
 app.use(async(req,res,next)=>{try{const user=await authenticate(req.headers.cookie);currentUser.run(user,()=>next());}catch{res.status(503).json({error:'Account service unavailable.'});}});
 app.get('/api/auth/me',async(_req,res)=>{const user=currentUser.getStore();if(!user)return res.status(401).json({error:'Sign in required'});res.json({name:user.fullName,email:user.email,role:await identity(user)});});
 app.post('/api/auth/accounts',async(req,res)=>{try{const user=currentUser.getStore();if(!user)return res.status(401).json({error:'Sign in required'});if(await identity(user)!=='admin')return res.status(403).json({error:'Administrator access required'});const body=z.object({email:z.string().email().max(254),password:z.string().min(12).max(200),name:z.string().min(1).max(100).optional(),department:z.string().min(1).max(80),role:z.enum(['admin','manager','learner'])}).parse(JSON.parse(req.body));await createAccount(body.email,body.name||'UBL Reviewer',body.password,body.role,body.department);return res.json({ok:true});}catch(e:any){return res.status(e.code==='23505'?409:400).json({error:e.code==='23505'?'An account already exists for that email.':e instanceof z.ZodError?'Use a valid email and a password of at least 12 characters.':'Account could not be created.'});}});
 function mount(path:string,handlers:{GET:()=>Promise<Response>;POST:(request:Request)=>Promise<Response>}){app.get(path,async(_req,res)=>send(res,await handlers.GET()));app.post(path,async(req,res)=>{const headers=new Headers();if(req.headers.origin)headers.set('origin',req.headers.origin);if(req.headers.authorization)headers.set('Authorization',req.headers.authorization);headers.set('Content-Type','application/json');const request=new Request(frontendOrigin+path,{method:'POST',headers,body:req.body});await send(res,await handlers.POST(request));});}
 mount('/api/learning',learning);mount('/api/admin',admin);mount('/api/advanced',advanced);mount('/api/reminders/run',{GET:async()=>new Response('Method not allowed',{status:405}),POST:reminders.POST});app.get('/api/assets/:id',async(req,res)=>send(res,await assets.GET(new Request(frontendOrigin+req.path),{params:Promise.resolve({id:String(req.params.id)})})));
 app.use((_req,res)=>res.status(404).json({error:'Route not found'}));app.use((err:any,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{console.error('Request failed:',err.name);res.status(err.type==='entity.too.large'?413:500).json({error:err.type==='entity.too.large'?'Request too large.':'Server request failed.'});});return app;}
async function send(res:express.Response,response:Response){res.status(response.status);response.headers.forEach((value,key)=>res.setHeader(key,value));res.send(Buffer.from(await response.arrayBuffer()));}
