import {AsyncLocalStorage} from 'node:async_hooks';
import {randomBytes,scrypt as scryptCallback,timingSafeEqual,createHash,randomUUID} from 'node:crypto';
import {pool} from './lib/database';
export type AppUser={userId:string;email:string;fullName:string|null;displayName:string};
export const currentUser=new AsyncLocalStorage<AppUser|null>();
export async function getCurrentUser(){return currentUser.getStore()||null;}
function derive(password:string,salt:string):Promise<Buffer>{return new Promise((resolve,reject)=>scryptCallback(password,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024},(error,hash)=>error?reject(error):resolve(hash)));}
export async function hashPassword(password:string){const salt=randomBytes(16).toString('hex');const hash=await derive(password,salt);return `scrypt$${salt}$${hash.toString('hex')}`;}
export async function verifyPassword(password:string,stored:string){try{const [kind,salt,value]=stored.split('$');if(kind!=='scrypt')return false;const expected=Buffer.from(value,'hex');const actual=await derive(password,salt);return expected.length===actual.length&&timingSafeEqual(expected,actual);}catch{return false;}}
export function tokenHash(token:string){return createHash('sha256').update(token).digest('hex');}
export function readToken(cookie:string|undefined){const match=cookie?.split(';').map(v=>v.trim()).find(v=>v.startsWith('learn_session='));return match?.slice('learn_session='.length)||null;}
export async function authenticate(cookie:string|undefined):Promise<AppUser|null>{const token=readToken(cookie);if(!token||!/^[a-f0-9]{64}$/.test(token))return null;const result=await pool.query('SELECT u.id,u.email,u.name FROM app_sessions s JOIN app_users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>$2',[tokenHash(token),new Date().toISOString()]);const row=result.rows[0];return row?{userId:row.id,email:row.email,fullName:row.name,displayName:row.name}:null;}
export async function createAccount(email:string,name:string,password:string,role:string,department:string){const client=await pool.connect();try{await client.query('BEGIN');const id=randomUUID();await client.query('INSERT INTO app_users (id,email,name,password_hash,created_at) VALUES ($1,$2,$3,$4,$5)',[id,email.toLowerCase(),name,await hashPassword(password),new Date().toISOString()]);await client.query('INSERT INTO members (email,user_id,name,role,department) VALUES ($1,$2,$3,$4,$5) ON CONFLICT(email) DO UPDATE SET user_id=excluded.user_id,name=excluded.name,role=excluded.role,department=excluded.department',[email.toLowerCase(),id,name,role,department]);await client.query('COMMIT');return id;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function seedAccounts(){const entries=[{email:process.env.BOOTSTRAP_ADMIN_EMAIL,password:process.env.BOOTSTRAP_ADMIN_PASSWORD,name:'Prototype Administrator',role:'admin'},{email:process.env.BOOTSTRAP_LEARNER_EMAIL,password:process.env.BOOTSTRAP_LEARNER_PASSWORD,name:'UBL Reviewer',role:'learner'}];for(const entry of entries){if(!entry.email&&!entry.password)continue;if(!entry.email||!entry.password||entry.password.length<12)throw new Error('Bootstrap accounts need an email and a password of at least 12 characters.');const existing=await pool.query('SELECT id FROM app_users WHERE email=$1',[entry.email.trim().toLowerCase()]);if(!existing.rows.length)await createAccount(entry.email.trim().toLowerCase(),entry.name,entry.password,entry.role,'UBL Demo');}}
export async function startSession(userId:string){const token=randomBytes(32).toString('hex');await pool.query('INSERT INTO app_sessions (token_hash,user_id,expires_at) VALUES ($1,$2,$3)',[tokenHash(token),userId,new Date(Date.now()+8*3600000).toISOString()]);return token;}
export const sessionCookie=(token:string,clear=false)=>`learn_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${clear?0:28800}${process.env.NODE_ENV==='production'?'; Secure':''}`;
