import {env} from '../lib/env';
import {emailReady} from '../lib/reminders';
import {getCurrentUser} from '../auth';
import {identity,settings,report,library} from '../lib/admin';
import {load} from '../lib/store';
import {database} from '../lib/store';
import {liveAvailable} from '../lib/generator';
import {provider,openAIExtrasReady} from '../lib/ai';
import {z} from 'zod';
export const dynamic='force-dynamic';
export async function GET(){const user=await getCurrentUser();if(!user)return Response.json({error:'Sign in required'},{status:401});try{const role=await identity(user);if(role==='learner')return Response.json({error:'Management access required'},{status:403});return Response.json({role,connections:{provider:provider(),ai:liveAvailable(),images:openAIExtrasReady(),realtime:openAIExtrasReady(),email:emailReady(),schedule:Boolean((env as any).REMINDER_JOB_SECRET),sso:false},settings:await settings(),learners:await report(),library:await library(),liveAI:liveAvailable()},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Reporting is temporarily unavailable.'},{status:503});}}
export async function POST(request:Request){const user=await getCurrentUser();if(!user)return Response.json({error:'Sign in required'},{status:401});if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin'},{status:403});try{if(await identity(user)!=='admin')return Response.json({error:'Administrator access required'},{status:403});const raw=await request.text();if(raw.length>15000)return Response.json({error:'Request too large'},{status:413});const body=JSON.parse(raw);if(body.action==='settings'){const value=z.object({language:z.enum(['English','Urdu','English + Urdu']),level:z.enum(['Beginner','Intermediate','Advanced']),duration:z.number().int().min(3).max(20),voice:z.boolean(),gamification:z.boolean(),reviewDays:z.number().int().min(1).max(7),audience:z.string().trim().min(2).max(120),tone:z.enum(['Supportive','Professional','Playful']),foundationThreshold:z.number().int().min(20).max(60),advancedThreshold:z.number().int().min(65).max(95),nudges:z.boolean()}).parse(body.settings);await database().prepare('INSERT INTO organization_settings (id,payload,updated_at) VALUES (\'default\',?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at').bind(JSON.stringify(value),new Date().toISOString()).run();}else if(body.action==='publish'){const department=z.string().trim().min(1).max(80).parse(body.department);const {state}=await load(user.userId);if(!state.course)throw new Error('Create a journey in the learner portal first.');await database().prepare('INSERT INTO content_library (id,title,department,language,level,payload,created_at) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),state.course.title,department,state.course.language,state.course.level,JSON.stringify(state.course),new Date().toISOString()).run();}else if(body.action==='unpublish'){const id=z.string().uuid().parse(body.id);await database().prepare('DELETE FROM content_library WHERE id=?').bind(id).run();}else if(body.action==='member'){const member=z.object({email:z.string().email().max(254),role:z.enum(['learner','manager','admin']),department:z.string().trim().min(1).max(80)}).parse(body.member);await database().prepare('INSERT INTO members (email,name,role,department) VALUES (?,\'Invited learner\',?,?) ON CONFLICT(email) DO UPDATE SET role=excluded.role,department=excluded.department').bind(member.email.toLowerCase(),member.role,member.department).run();}else throw new Error('Unknown action');return Response.json({ok:true});}catch(e){return Response.json({error:e instanceof z.ZodError?'Check the settings values.':(e as Error).message},{status:400});}}
