import type {ExtractedDocument} from './source';
let ocrModule:Promise<any>|null=null;
export async function recognizeImage(input:any,language:string,onProgress:(message:string)=>void){ocrModule??=import('tesseract.js');const {createWorker}=await ocrModule;const worker=await createWorker(language==='Urdu'?'urd':language==='English + Urdu'?['eng','urd']:'eng',1,{workerPath:'/ocr/worker.min.js',corePath:'/ocr/core',langPath:'/ocr/lang',logger:(m:any)=>onProgress(m.status+' '+Math.round((m.progress||0)*100)+'%')});try{return (await worker.recognize(input)).data.text as string;}finally{await worker.terminate();}}
export async function extractDocument(file:File,onProgress:(message:string)=>void,language='English'):Promise<ExtractedDocument>{
 if(file.size>5*1024*1024)throw new Error('Choose a document smaller than 5 MB.');if(file.size===0)throw new Error('This document is empty.');if(!/\.(pdf|docx|txt|md|png|jpe?g|webp)$/i.test(file.name))throw new Error('Choose a PDF, DOCX, TXT, Markdown or image document.');
 let pages:ExtractedDocument['pages'];let referenceKind:'page'|'section'='page';let usedOCR=false;
 if(/\.pdf$/i.test(file.name)){
 const data=new Uint8Array(await file.arrayBuffer());if(new TextDecoder().decode(data.slice(0,5))!=='%PDF-')throw new Error('This file is not a valid PDF.');onProgress('Opening PDF…');const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';const task=pdfjs.getDocument({data,useSystemFonts:true,disableFontFace:true,useWasm:false});let pdf;try{pdf=await task.promise;}catch(e){await task.destroy();if((e as Error).name==='PasswordException')throw new Error('This PDF is password protected. Upload an unlocked copy.');throw new Error('The PDF could not be read. Try exporting a fresh PDF or upload text.');}
 pages=[];let characters=0,scans=0;
 try{if(pdf.numPages>100)throw new Error('This prototype supports up to 100 pages.');for(let page=1;page<=pdf.numPages;page++){onProgress(`Reading page ${page} of ${pdf.numPages}…`);const current=await pdf.getPage(page);const content=await current.getTextContent();let text=content.items.map(item=>'str' in item?item.str+((item as any).hasEOL?'\n':' '):'').join('').trim();if(text.length<40&&typeof globalThis.document!=='undefined'){if(++scans>10)throw new Error('OCR supports up to 10 scanned pages per upload. Split this document into smaller sections.');const view=current.getViewport({scale:Math.min(2,1800/Math.max(current.view[2],current.view[3]))});const canvas=globalThis.document.createElement('canvas');canvas.width=Math.ceil(view.width);canvas.height=Math.ceil(view.height);const context=canvas.getContext('2d');if(!context)throw new Error('Image rendering is unavailable.');await current.render({canvas,canvasContext:context,viewport:view}).promise;text=await recognizeImage(canvas,language,m=>onProgress(`Page ${page}: ${m}`));canvas.width=canvas.height=0;usedOCR=true;}characters+=text.length;if(characters>80000)throw new Error('Use fewer than 80,000 characters.');pages.push({page,text});current.cleanup();}}finally{await task.destroy();}
 }else if(/\.docx$/i.test(file.name)){onProgress('Reading Word document…');const data=await file.arrayBuffer();const {unzipSync}=await import('fflate');let total=0;const entries=unzipSync(new Uint8Array(data),{filter:entry=>{total+=entry.originalSize;if(total>16*1024*1024)throw new Error('This Word document expands beyond the supported size.');return false;}});void entries;const library=await import('mammoth/mammoth.browser.js');const mammoth=(library as any).default||library;const result=await mammoth.extractRawText({arrayBuffer:data});referenceKind='section';pages=[{page:1,text:result.value}];
 }else if(/\.(png|jpe?g|webp)$/i.test(file.name)){onProgress('Recognizing image text…');const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>16000000)throw new Error('Use an image smaller than 16 megapixels.');pages=[{page:1,text:await recognizeImage(file,language,onProgress)}];usedOCR=true;}finally{bitmap.close();}
 }else{onProgress('Reading document text…');referenceKind='section';pages=[{page:1,text:await file.text()}];}
 const length=pages.reduce((n,p)=>n+p.text.length,0);if(length<200)throw new Error('Not enough readable text was found. Use a clearer scan or a document with at least 200 characters.');if(length>80000)throw new Error('Use fewer than 80,000 characters.');return {filename:file.name,pages,referenceKind,usedOCR};
}
